# make sure you add any library we may need
ARDUINO_DIR = /usr/share/arduino
BOARD_TAG    = mega2560
ARDUINO_PORT = /dev/ttyACM1
ARDUINO_LIBS = Servo Wire Wire/utility ros_lib
include /usr/share/arduino/Arduino.mk
